apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendezvous-service
  labels:
    app: rendezvous-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendezvous-service
  template:
    metadata:
      labels:
        app: rendezvous-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: rendezvous-service
          image: rendezvous-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: rendezvous-config-volume
          configMap:
            name: rendezvous-config