apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendezvous-service
  labels:
    app: rendezvous-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendezvous-service
  template:
    metadata:
      labels:
        app: rendezvous-service
    spec:
      containers:
        - name: rendezvous-service
          image: rendezvous-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: RENDEZVOUS_PARTICIPANT_SERVICE_URI
              value: http://participant-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_RABBITMQ_HOST
              value: rendezvous-rabbitmq
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://rendezvous-postgres/rendezvousdb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://rendezvous-postgres/rendezvousdb_order
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://rendezvous-keycloak/realms/RendezvousTech